### ISSUE TITLE
Wrong item total in the receiving receipt

### ISSUE THREAD

**Issue by freemail624** [jekkos/opensourcepos#1233]
The problem happen when you scan or enter the item to increase the qty  
But no problem if you edit the quantity manual 
Ex:
Try to enter one item 4 times to make the qty 4 but don't edit the qty to become 4
I tested this with the last version
![receivings](https://cloud.githubusercontent.com/assets/6794450/25017033/edbc7b5a-208a-11e7-93f3-a506f0c08274.jpg)

 look at the total in the sessions
![sessions](https://cloud.githubusercontent.com/assets/6794450/25017035/f1b2c9da-208a-11e7-8714-55cc411a3786.jpg)

 look at the item total in the receipt
![receipt](https://cloud.githubusercontent.com/assets/6794450/25017041/f5b7a6e0-208a-11e7-8f60-52b18aecace2.jpg)

**Comment by daN4cat** [comment]
Good one, well done.

**Comment by jekkos** [comment]
Some profound testing going on here.

**Comment by SteveIreland** [comment]
I tested this scenario in the customer sales branch and it appears to be working.

**Comment by daN4cat** [comment]
@SteveIreland you mean your branch? If so I just merged and this should be fixed then.

**Comment by odiea** [comment]
I still get this issue. It is on the line item and not the total.
![2017-04-15 05_30_41-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/25063267/e266f6fa-219c-11e7-8dff-1f4fd6186343.png)

**Comment by odiea** [comment]
And yes I did a merge  this morning.

**Comment by SteveIreland** [comment]
@odiea Sorry, I'm not able to replicate the issue.  I'm adding the same item multiple times by enter the item code and pressing Enter.  The register, receipts (both default and short) show the correct extended line amount.  Is there additional information about the configuration that might help me recreate the issue:?

**Comment by freemail624** [comment]
@SteveIreland  This happen in the receiving not in sales

**Comment by SteveIreland** [comment]
Oh ... duh ... sorry, I've been a bit slow on the uptake over the last couple of weeks.  Hopefully this doesn't become a permanent part of my behavior.

**Comment by SteveIreland** [comment]
I could be wrong, but I think this issue existed before my changes and probably should have fallen into the group of issues delineated on #1199.  But it is definitely fixed with this pull request.

**Comment by odiea** [comment]
Fixed.

**Comment by daN4cat** [comment]
You mean the change I just merged is the fix. Right?
