### ISSUE TITLE
Can't select payment type for sale returns

### ISSUE THREAD

**Issue by esbyrt** [jekkos/opensourcepos#1384]
###Issue / Question / Bug

Before submitting an issue please make sure you tick (add a x between the square brackets with no spaces) the following check boxes:

 I'm reporting an issue of an unmodified OSPOS installation
 I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
 I read the README, WHATS_NEW and UPGRADE
 I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
 I read the wiki
 I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
 I'm aware the latest master could be a development version and therefore not stable
 I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

###Installation information

OSPOS version is: 3.2.2
OSPOS git commit hash is: 4f5ad57
PHP version is: (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.3
MySQL or MariaDB version is: (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0.31
OS and version is: (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
WebServer is: (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.25
(If applicable) Installation package for the LAMP/LEMP stack is: (e.g. WAMP, XAMPP)

### Expected behaviour
When entering a sales return I bring up the original sale by POS 46 for example. The items fill in with negative quantities as expected. But when I go to select payment type the mouse cursor turns to a red circle with a line across it and I can't change payment type. Is this by design? It would be nice to record if the refund was processed on credit card or cash. Also when returning an item that was purchased with a gift card is there a way to put the credit back on the gift card?
Thanks!

**Comment by daN4cat** [comment]
There is no OSPOS 3.2.2 version. Are you using an original?

**Comment by esbyrt** [comment]
Sorry it is 3.0.2

**Comment by RamkrishnaMondal** [comment]
Look here and change the related files accordingly: https://github.com/jekkos/opensourcepos/commit/53dcdc02cfd47564e44f1f97102c4dafce3e7706

**Comment by daN4cat** [comment]
Right 3.0.2 had that big and I fixed twice in 3.1.0

**Comment by esbyrt** [comment]
daN4cat - my apologies. I have looked all over the site for updates and haven't been able to find one. I guess I'm not looking in the right place. Still can't find it.

**Comment by esbyrt** [comment]
RamkrishnaMondal thanks for pointing me in the right direction. Just one question ( I am not a programmer and new to OSPOS) are the lines in red to be deleted and replaced with the lines in green?

**Comment by daN4cat** [comment]
@esbyrt yes the red goes and the green replaces it.
