### ISSUE TITLE
Search item not work

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#406]
search item not work on my ospos v2.3.4, but i forgot when I downloaded it. I do not know whether it has been resolved. I do not find the issue about search items
![search_item](https://cloud.githubusercontent.com/assets/17277219/13897002/86a4bc10-edd3-11e5-8138-c0a0e124d341.png)

**Comment by daN4cat** [comment]
Bootstrap UI cannot be 2.3.4

**Comment by daN4cat** [comment]
By the way, 3.0 works fine but the bulk edit issue and proper template support. What's left more are new tables and charts. Of course other new functionality.

**Comment by arkgnan** [comment]
i also download master (2.4), and doing fresh installation but search item still not work
![ospos2 4](https://cloud.githubusercontent.com/assets/17277219/13909880/cda7a5b2-ef4c-11e5-94f1-7363d6d8a023.png)

**Comment by daN4cat** [comment]
Have you checked if in the debugger something is reported?

**Comment by daN4cat** [comment]
I mean some js error.

**Comment by arkgnan** [comment]
search function is work, i must push enter after type the word in search field. the issue is in autocomplete, in other menu search menu use autocomplete... not sure if this version don't show suggestion

**Comment by daN4cat** [comment]
again, have you checked the Chrome inspect console? Any error or warning reported?

**Comment by arkgnan** [comment]
debugger not show any error... and autocomplete is work, but wrong data. as you can see in pict, it show supplier data in suggestion
![ospos2 4_item](https://cloud.githubusercontent.com/assets/17277219/13913764/56edcb42-ef7c-11e5-9341-a277cf63a078.png)
![ospos2 4_supplier](https://cloud.githubusercontent.com/assets/17277219/13913765/5740b8d4-ef7c-11e5-8d3f-41c45e18f027.png)

**Comment by daN4cat** [comment]
To see supplier in suggestion is correct.
Therefore this means something is not right with the items data.

Have you created the items from OSPOS or transferred from another database?
Do you see anything in the inventory of those items?

**Comment by arkgnan** [comment]
in this example. asus created from ospos, imac is from import template

On Mon, Mar 21, 2016 at 4:19 PM, FrancescoUK <notifications@github.com>
wrote:

> To see supplier in suggestion is correct.
> Therefore this means something is not right with the items data.
>
> Have you created the items from OSPOS or transferred from another database?
> Do you see anything in the inventory of those items?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/406#issuecomment-199188064>
>



-- 
Best Regards

Dedi Ananto

**Comment by daN4cat** [comment]
At the moment you are the only one able to reproduce this. We are trying to understand how.

**Comment by arkgnan** [comment]
issue solved in bootstrapUI branch, what different in master 2.4?

**Comment by daN4cat** [comment]
Do you have the issue even with PHP 5.5+ ?

**Comment by arkgnan** [comment]
no,I think I found the cause of issue. in 2.4, value of checkbox deleted always 1. so the query search item where deleted=1. not sure whats wrong in items controller or view.
the view is same between bootstrapUI and master 2.4. different of controller is in code : 
`$this->input->post('is_deleted') != null` and `'is_deleted' => !empty($this->input->post('is_deleted')`

**Comment by daN4cat** [comment]
I'll check this later.

**Comment by daN4cat** [comment]
Try replacing` !empty($this->input->post('is_deleted')` with $`this->input->post('is_deleted') != null`

**Comment by jekkos** [comment]
Yes something stupid going on here.. I think the is_deleted was checked is empty (so "", or 0) and then inverted. I believe I fixed that during the jquery upgrade.

**Comment by daN4cat** [comment]
I remember I changed to `$this->input->post('is_deleted') != null`, it might be that one was a miss?

**Comment by arkgnan** [comment]
when i debug is_deleted checked or not always have value 1

**Comment by daN4cat** [comment]
@arkgnan try the fix I pushed, see if it works for you. I cannot reproduce your issue so you are the only tester to prove it's right.

**Comment by arkgnan** [comment]
if i change to !empty i get issue PHP 5.5, and still not work. if the code change to `$this->input->post('is_deleted')` is_deleted value is 0, and if i add !=NULL, value change to be 1. i don't know the workflow, in my mind if we check is_deleted and we search, we got suggestion item name with deleted 1, and if we uncheck it we got suggestion item data with deleted value is 0, is right?
by the way, how about your place? is ospos 2.4 working properly, especially in suggestion item?

**Comment by daN4cat** [comment]
The suggestion is restricted to deleted or not deleted items according to how you set the check.

I'm afraid the issue you experience is probably related to some old PHP and setup. I cannot assist you on that, you probably need to decide what's best. This is just a pastime activity and there is no aim on my side to be perfect for every installation. Something needs to come from other sides too.

**Comment by arkgnan** [comment]
how about this
`$("#is_deleted").change(function() {
        widget.flushCache();
    });`
i can't found it on bootstrapUI (view->item->manage)

**Comment by daN4cat** [comment]
That's removed because the table sorter was updated to a latest version. Requires jQuery 1.12.x

**Comment by daN4cat** [comment]
I believe this is a specific configuration issue, I fixed in the same way as in bootstrapUI so I can close this.

**Comment by arkgnan** [comment]
for me i remove !=null and it work perfect.
original code `$this->input->post('is_deleted')!=NULL`
i change to be `$this->input->post('is_deleted')`
