### ISSUE TITLE
Email receipt not sent

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#519]
hi, is there any one having issue like me. i use ospos 3 (for now i use all file in master) when i check up email receipt and complete sale i didn't get any email

**Comment by daN4cat** [comment]
Works fine for me. Have you checked your email configuration?

**Comment by arkgnan** [comment]
you mean email email configuration in system->library->email.php? i use original file from master so the config is still default. whether the default configuration is still not able to send email? if not how must i change email configuration

**Comment by jekkos** [comment]
There are different mechanisms to send mail from php. Normally CI uses the standard php configuration. Check if your php config is able to send emails.

If not then check in application/config/email.php. If not present then copy the template to that location and fill in the right credentials.

**Comment by arkgnan** [comment]
Do you have an example template? if i use mail function from basic php like this
`mail($to,$subject,$message,$headers);`
it can send email, but if i used mail function from ci library i can't send email

**Comment by daN4cat** [comment]
Issue #441 should solve this. @ais-one any progress with that?

**Comment by arkgnan** [comment]
still not sent with gmail(smtp alway time out), but success when use email with custom domain configuration

**Comment by RamkrishnaMondal** [comment]
smtp_host : "smtp.gmail.com"
smtp port: 587

works for me.

**Comment by arkgnan** [comment]
i'll try, i use post 465 for ssl gmail

**Comment by RamkrishnaMondal** [comment]
https://jacmoe.dk/blog/2013/january/how-to-send-emails-with-msmtp-on-windows-or-linux-or-mac-os-x

**Comment by daN4cat** [comment]
Sorted in #411. I close.

**Comment by paisapimp** [comment]
My solution was to use phpMailer

replace the default function with this one on: application->libraries->Email_lib.php

` public function sendEmail($to, $subject, $message, $attachment = NULL)
    {
        require 'class.smtp.php'; 
	require 'class.phpmailer.php';
        $mail = new PHPMailer();
        $mail->isSMTP();
        $mail->SMTPDebug = 0;
		$mail->Debugoutput = 'html';
        $mail->SMTPAuth = true;
        $mail->Host = "Your Host";
        $mail->Port = 25;
        $mail->addAddress($to);
		if(!empty($attachment))
		{
			$mail->addStringAttachment($attachment);
		}
		$mail->Username = "no-reply@domain.com";
		$mail->Password = "123345";
		$mail->setFrom('no-reply@domain.com', 'SPA 5 Elementos & Centro de Belleza');
		$mail->addReplyTo('no-reply@domain.com', 'SPA 5 Elementos & Centro de Belleza');
        $mail->Subject = $subject;
        $mail->msgHTML($message);
        $mail->send();
		$result = $mail->send();
		if(!$result)
		{
			error_log($email->print_debugger());
		}
		return $result;
		
    }`

**Comment by blutme** [comment]
[https://www.alvarolara.com/2014/02/15/enviar-emails-desde-localhost-con-php-y-msmtp/](url)

![Captura de pantalla (26)](https://user-images.githubusercontent.com/29499149/67361345-fab4d800-f52d-11e9-8834-857b8c1e80a2.png)

This method worked well for me!
