### ISSUE TITLE
Store Config and Receiving

### ISSUE THREAD

**Issue by gfxgee** [jekkos/opensourcepos#655]
this error message should be in general tab and no success message every time i submit. thanks sir! 

![image](https://cloud.githubusercontent.com/assets/8316409/16069959/e81adcc4-3304-11e6-861d-66bdec43619c.png)

**Comment by gfxgee** [comment]
When I try to return the items using item kits, it gives me this error :confused: 

![image](https://cloud.githubusercontent.com/assets/8316409/16072494/b59bd0b4-3313-11e6-976a-1145ba28914d.png)

**Comment by odiea** [comment]
It appears the Receiving issue is a bug. I also get that issue to show trying to return a Kit.

**Comment by jekkos** [comment]
Ok thanks for reporting this bug. Will have a look later today.

**Comment by jekkos** [comment]
First issue should be fixed, will look into second now.

**Comment by jekkos** [comment]
There you go, should be both fixed now. That second bug dated back from some time ago (more than a year or sometihng).. 

Guess that means item kits aren't really used that much (until recently a lot of questions / bug reports regarding this functionality)

**Comment by daN4cat** [comment]
That means new OSPOS is getting popular....

**Comment by odiea** [comment]
I am still having the same issues when you try to use return on an Item kit. Only 1 of the items show and I still get this error.
![2016-06-15 14_26_54-program manager](https://cloud.githubusercontent.com/assets/10962177/16096254/5b167f80-3305-11e6-9228-5dfbc05a7bf4.png)

**Comment by gfxgee** [comment]
thank you so much for the fix sir :+1:

**Comment by gfxgee** [comment]
hmm i replace the old method by this and it works fine somehow , i don't know if this totally works, any update guys? or correct me if im wrong :confounded: 
```
public function get_receiving_items_2($receiving_id)
	{
		return $this->db->query("SELECT 
		  oikt.`item_kit_id`,
		  oikt.`quantity` AS `quantity_purchased`,
		  ori.`description`,
		  ori.`discount_percent`,
		  oi.`cost_price` AS`item_cost_price`,
		  ori.`item_id`,
		  ori.`item_location`,
		  oi.`unit_price` AS `item_unit_price`,
		  ori.`line`,
		  ori.`receiving_id`,
		  oi.`receiving_quantity`,
		  ori.`serialnumber` 
		FROM
		  ospos_item_kit_items oikt,
		  ospos_receivings_items ori,
		  ospos_items oi
		WHERE oikt.`item_id` = ori.`item_id`
		  AND oikt.`item_id` = oi.`item_id` 
		  AND item_kit_id = ".$receiving_id." 
		GROUP BY oikt.`item_id` ");
	}
```

**Comment by daN4cat** [comment]
The principle might be right but it's a bad idea to build queries like those in OSPOS .

**Comment by jekkos** [comment]
I've done another fix for the item kit return. Something was wrong in the return flow as the first is_valid_receipt check wasn't the same as the one doing the actual return. In the latter case the flow seemed to try and return an receiving with invoice number that might not have been necessarily there. 

As a side effect you might not be able to return what you were trying to return (at least if I understood your stacktrace correctly)

**Comment by jekkos** [comment]
Guess we can close now
