### ISSUE TITLE
Deleted Item Deleted from Receipt

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#904]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web install using Docker Cloud

### Expected behaviour

Receipts are stable and do not change when its items are deleted

### Actual behaviour

When I delete an item it is deleted from receipts that reference that item

### Steps to reproduce the issue

1. Create new item A
2. Sell Item A
3. Delete Item A
4. Search Detailed Reports
5. The information on the table is correct even though the item is deleted. However, if the actual receipt is viewed, then the item is missing and there is change due equal to the value of the item.

**Comment by daN4cat** [comment]
Sale receipt?

**Comment by petercstevenson** [comment]
Yes, I am referring to the sales receipt

**Comment by jekkos** [comment]
Shall we solve this one before release?

**Comment by daN4cat** [comment]
I would say yes.

**Comment by onyema3** [comment]
yes

**Comment by petercstevenson** [comment]
The reason why this is so important for me is that I don't feel comfortable deleting items right now so that leaves a huge cumbersome low stock list that I have to manually sort through every time I do an order from a supplier

**Comment by daN4cat** [comment]
This needs to be fixed because when I migrate my wife's system to this I have many old receipts pointing to deleted (but still in MySQL) items.

**Comment by daN4cat** [comment]
I believe I fixed this, see last commit to master.
Please test and confirm that it's fine an we can close.

It would be good to do a test in Sales with transactions using barcode and item name as the changed part is in common with that functionality. The same on Receivings.

I tested and it's fine for me but better to have more testers.

**Comment by odiea** [comment]
Looks good. Item does not show up in Register or Receiving (after deleting) using either the item id or the item name. It still shows on the receipt ok. I have not a scanner available to use.

**Comment by petercstevenson** [comment]
It seems fixed to me. Thanks

**Comment by petercstevenson** [comment]
Sorry, I just realized that although the item is now shown in the sales receipt, it is still not shown in the receivings receipt

**Comment by daN4cat** [comment]
Ok, I'll check that case.

**Comment by daN4cat** [comment]
Fixed Receiving case too.

Please test all the receiving cases so we can close this.

**Comment by odiea** [comment]
Looks good. Ran a receivings report and deleted item shows in the report. I don't use this so I forgot to check the receiving report.

**Comment by daN4cat** [comment]
@petercstevenson please countercheck but meanwhile I close this.

**Comment by petercstevenson** [comment]
Yes this seems fixed.
