### ISSUE TITLE
Error uploading Company Logo using Docker Web

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#917]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Docker web

### Expected behaviour

Company logo uploads

### Actual behaviour

When I upload a picture and then click on Submit I get the error message "The upload destination folder does not appear to be writable

### Steps to reproduce the issue

This may just be a Docker issue

**Comment by petercstevenson** [comment]
BTW, I don't really need this functionality - I just thought that the developers should know that this doesn't work using the Docker web setup.

**Comment by jekkos** [comment]
I've changed permissions on the upload folder in the Dockerfile. Can someone verify if this is ok?

**Comment by daN4cat** [comment]
@jekkos something is now wrong with TravisCI, it fails or hangs.

**Comment by jekkos** [comment]
I tested on local and upload works now in the container. I close. Travis build is fixed as well.

**Comment by petercstevenson** [comment]
This still does not work in my configuration - I get the same error message.

**Comment by jekkos** [comment]
@petercstevenson issue is that you'll need to recreate the data container (and might lose you're data). You can set the file permissions manually on your container which should fix the issue after all.

**Comment by petercstevenson** [comment]
Permissions for /app/uploads/ and /app/public/uploads/ are already set to 775. If the only way to get this to work is to risk losing my data, it's not worth it to me.

**Comment by jekkos** [comment]
OK but in that case it should just work.

**Comment by daN4cat** [comment]
@jekkos I believe the issue is not docker but the application that with composer change cannot access the  uploads dir. It's connected to the other issue with images not loadable in items.

**Comment by daN4cat** [comment]
ownership of the public dir needs to be correct too and permission set to 755, same applies to public subdirs too.

**Comment by petercstevenson** [comment]
The permissions of all of the subdirecties in /app/public were already set to 775

**Comment by daN4cat** [comment]
Have you even tried 777 to check no ownership aspect is affecting your issue?

**Comment by petercstevenson** [comment]
Thanks, @daN4cat. That fixed it. I changed the permissions of /app/public, /app/uploads, and /app/public/uploads to 777 and now it works.

**Comment by daN4cat** [comment]
Ok, but that means the ownership and group are not matching the web server one. It should be fixed and the set 755
